// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSKfUPj8KOPUK2ra8k8e50INsQ9tghls',
    appId: '1:790507994307:web:373e7a7771efa626f47676',
    messagingSenderId: '790507994307',
    projectId: 'signin-efc4d',
    authDomain: 'signin-efc4d.firebaseapp.com',
    storageBucket: 'signin-efc4d.appspot.com',
    measurementId: 'G-L7JLCQ9TL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSR6dR7JtX7jK8XYGbNT7ogNJR_PtVtF0',
    appId: '1:790507994307:android:14f8d1907b1c7a5cf47676',
    messagingSenderId: '790507994307',
    projectId: 'signin-efc4d',
    storageBucket: 'signin-efc4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0UrySOFnxWC9tyZ1yferVTeG8cO0kek',
    appId: '1:790507994307:ios:6e93f52ca9fc23fff47676',
    messagingSenderId: '790507994307',
    projectId: 'signin-efc4d',
    storageBucket: 'signin-efc4d.appspot.com',
    androidClientId: '790507994307-4950uu6ebtf5oa8dfmo2ns3otf3h2tn7.apps.googleusercontent.com',
    iosClientId: '790507994307-j4njmsrg67lhtvb3id6dajlu62k6reqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa0UrySOFnxWC9tyZ1yferVTeG8cO0kek',
    appId: '1:790507994307:ios:6e93f52ca9fc23fff47676',
    messagingSenderId: '790507994307',
    projectId: 'signin-efc4d',
    storageBucket: 'signin-efc4d.appspot.com',
    androidClientId: '790507994307-4950uu6ebtf5oa8dfmo2ns3otf3h2tn7.apps.googleusercontent.com',
    iosClientId: '790507994307-j4njmsrg67lhtvb3id6dajlu62k6reqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.signinfire',
  );
}
